import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: 24,
        justifyContent: 'center',
        gap: 16,
        alignItems: 'center',
        backgroundColor: '#2a003f',
    },
    welcomeText: {
        fontSize: 18,
        color: '#ffffff',
        marginBottom: 16,
    },
    detailsContainer: {
        width: '100%',
        backgroundColor: '#3a005c',
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#bb86fc',
    },
    detailsTitle: {
        fontSize: 16,
        color: '#ffffff',
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    detailLabel: {
        fontSize: 14,
        color: '#bb86fc',
        fontWeight: 'bold',
    },
    detailValue: {
        fontSize: 14,
        color: '#ffffff',
    },
    checkpointsContainer: {
        marginTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#bb86fc',
        paddingTop: 12,
    },
    checkpointsTitle: {
        fontSize: 14,
        color: '#bb86fc',
        fontWeight: 'bold',
        marginBottom: 8,
    },
    checkpointItem: {
        backgroundColor: '#4a006c',
        borderRadius: 6,
        padding: 10,
        marginBottom: 8,
    },
    checkpointSite: {
        fontSize: 14,
        color: '#ffffff',
        fontWeight: 'bold',
    },
    checkpointMotivo: {
        fontSize: 12,
        color: '#bbbbbb',
    },
    checkpointTime: {
        fontSize: 12,
        color: '#bb86fc',
        textAlign: 'right',
    },
    input: {
        borderWidth: 1,
        borderColor: '#bb86fc',
        borderRadius: 8,
        padding: 14,
        marginRight: 9,
        width: '50%',
        maxWidth: 300,
        backgroundColor: '#3a005c',
        color: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    pickerContainer: {
        width: '100%',
        maxWidth: 300,
        borderRadius: 8,
        overflow: 'hidden',
        backgroundColor: '#3a005c',
        borderColor: '#bb86fc',
        borderWidth: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    picker: {
        color: '#fff',
        backgroundColor: '#3a005c',
        height: 50,
    },
    button: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
        width: '100%',
        maxWidth: 300,
    },
    buttonStart: {
        backgroundColor: '#03dac5',
    },
    buttonStop: {
        backgroundColor: '#e32636',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    buttonCheckpoint: {
        backgroundColor: '#6200ee',
    },
    buttonDisabled: {
        backgroundColor: '#555',
    },
    imageButton: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#3700B3',
        marginVertical: 10,
        width: '100%',
        maxWidth: 300,
    },
    imagePreview: {
        width: 200,
        height: 200,
        borderRadius: 8,
        marginVertical: 10,
        borderWidth: 1,
        borderColor: '#bb86fc',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
        width: '80%',
        backgroundColor: '#2a003f',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 18,
        color: '#ffffff',
        marginBottom: 20,
        fontWeight: 'bold',
    },
    modalInput: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#bb86fc',
        borderRadius: 8,
        padding: 10,
        backgroundColor: '#3a005c',
        color: '#ffffff',
        marginBottom: 20,
    },
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    modalButton: {
        padding: 10,
        borderRadius: 8,
        width: '48%',
        alignItems: 'center',
    },
    modalButtonCancel: {
        backgroundColor: '#e32636',
    },
    modalButtonConfirm: {
        backgroundColor: '#03dac5',
    },
    modalButtonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    siteInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    pickerContainerUF: {
        width: '100%',
        maxWidth: 120,
        borderRadius: 8,
        overflow: 'hidden',
        backgroundColor: '#3a005c',
        borderColor: '#bb86fc',
        borderWidth: 1,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    ufPicker: {
        height: 50,
        color: '#fff',
        backgroundColor: '#3a005c',
        borderWidth: 1,
        borderColor: '#bb86fc',
        borderRadius: 8,
    },
    buttonPanic: {
        backgroundColor: 'red',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 10,
    },
    panicButton: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: '#fff8f824',
        borderColor: '#FFF',
        borderWidth: 2,
        borderRadius: 50,
        borderStyle: 'dashed',
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5, // Para adicionar sombra no Android
        shadowColor: '#000', // Para adicionar sombra no iOS
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
    },
});

export default styles;